### ISSUE TITLE
Bot can't enter voice channels after command spam

### ISSUE THREAD

**Issue by Pico143** [Dank-Memer/Dank-Memer#184]
Hey,

Me and my friends spammed pls fart a little bit too much (and did it from many text channels at once) and Dank Memer got tired of our shit. All of a sudden, he wouldn't join any voice channel in our discord with any sound command. We removed him and reinvited him, but it's the same problem. Bot itself claims to work properly (he answers pls fart, pls mememusic etc. as usual). 

What's going on here?

Edit: just to mention, issue is ongoing for over 24 hours, it's not just temporary.

**Comment by zBlakee** [comment]
We're aware of this issue and we're currently working towards fixing it. Although more testing needs to be done, command spam likely isn't the main culprit of the issue (and we don't necessarily encourage it).
