### ISSUE TITLE
Feature request: Vsauce

### ISSUE THREAD

**Issue by cole21771** [Dank-Memer/Dank-Memer#47]
-memgen
-Voice channel and says random things (such as "Where are your fingers?")
-Maybe it responds with those random things ^
-Maybe random facts (possibly unrelated to vsauce)

**Comment by melmsie** [comment]
I will look into this a bit and get back to you

**Comment by melmsie** [comment]
After looking into this, I've decided there isn't enough need for this. Thank you for you idea though.
