### ISSUE TITLE
Feature request: byemom meme editing tommy to discord username/nickname

### ISSUE THREAD

**Issue by architdate** [Dank-Memer/Dank-Memer#48]
So instead of `Alright tommy im leaving the house` it would add the discord username or nickname to it instead of `tommy` :]

**Comment by melmsie** [comment]
Not the worst idea, will look into it!

**Comment by melmsie** [comment]
As of right now we're having issues doing this with our current image manipulation library. Soon we will hopefully be moving to a new one that will give us more freedom. As this is now on our list as something that will be added, I'm going to close the issue. But it's coming.
