### ISSUE TITLE
Memes don't have images attached to them?

### ISSUE THREAD

**Issue by TarekSalama** [Dank-Memer/Dank-Memer#55]
So I gave the bot all the permissions it needs and I even tried it on an empty channel but it seems to have stopped attaching images for each meme it posts. Discord members will need to click the link and open it in their browser in order to see the meme.

`pls magik` works fine and it attaches the image correctly. So I'm assuming it's a bug?

**Comment by xXBuilderBXx** [comment]
This is a bug with Reddits API and the bot creator Melmsie already knows about it.

**Comment by DaJuukes** [comment]
Yes this is a Reddit API issue; not ours.
