### ISSUE TITLE
I just lost ALL my coins.

### ISSUE THREAD

**Issue by irman** [Dank-Memer/Dank-Memer#76]
Guys, halp. Why did I lose all my coins for no reason?

From:
![image](https://user-images.githubusercontent.com/6107943/37883045-c99e930a-30da-11e8-9d31-16bc7bc103f9.png)

To:
![image](https://user-images.githubusercontent.com/6107943/37883072-e1420ff0-30da-11e8-9f4a-0619b1ec9296.png)

![image](https://user-images.githubusercontent.com/6107943/37883084-f407eb0a-30da-11e8-8e76-d8dd90d4f349.png)

With no reason at all. All my hard work. T.T

You can check your logs (if you have any) if you didn't trust the screenshot.

**Comment by melmsie** [comment]
You are still the only person to have this happen to them. The code doesn't
make sense with your screenshots so I can't help you right now.

**Comment by irman** [comment]
If it helps, there's some begging and searching from me between those 2 screenshots. And also other people's gambling and memeing.

**Comment by JuanPablo2655** [comment]
Probably someone stole from you?

**Comment by irman** [comment]
Didn't think so, here's the full screenshot:

![image](https://user-images.githubusercontent.com/6107943/37883978-3ff45aee-30e0-11e8-9f3c-0ce8fd4be1dc.png)

**Comment by melmsie** [comment]
Until more people report this, I have no way of seeing what it is. Will just have to wait and see.
