### ISSUE TITLE
Bug #1

### ISSUE THREAD

**Issue by melmsie** [Dank-Memer/Dank-Memer#78]
> Error: Voice connection timeout
>     at Timeout.pendingGuilds.(anonymous function).timeout.setTimeout [as _onTimeout] (/home/dank-memer/Dank-Memer/node_modules/eris/lib/voice/VoiceConnectionManager.js:47:25)
>     at ontimeout (timers.js:466:11)
>     at tryOnTimeout (timers.js:304:5)
>     at Timer.listOnTimeout (timers.js:267:5)

Seems to be fixed ~50% of the time by kicking the bot and re-adding it.

We use latest eris + eris-sharder

Happens to any of the voice commands [that can be found here](https://github.com/Dank-Memer/Dank-Memer/tree/master/src/commands/voiceCommands) and the voice handler can be [found here](https://github.com/Dank-Memer/Dank-Memer/blob/master/src/models/GenericVoiceCommand.js)

**Comment by melmsie** [comment]
@Marcus-Roman what?

**Comment by Marcus-Roman** [comment]
@melmsie unmute me on discord bots server

**Comment by MrJacz** [comment]
Just under https://github.com/Dank-Memer/Dank-Memer/blob/master/src/models/GenericVoiceCommand.js#L51 if you add a setTimeout this error should be fixed... It's from trying to play something when the bot hasn't properly connected yet
Probably something like ```javascript
// top of file
const delayer = ms => new Promise(res => setTimeout(() => res(), ms))
// Under joinVoiceChannel
await delayer(350)
```

**Comment by melmsie** [comment]
@MrJacz Will try this and get back to you after updating. Seems like it might just work though.

**Comment by Articuno1234** [comment]
add a loop to constantly try until it completes the task

**Comment by MrJacz** [comment]
Thats a bad idea.
