### ISSUE TITLE
Bug #2

### ISSUE THREAD

**Issue by melmsie** [Dank-Memer/Dank-Memer#79]
What the console spam [looks like](https://i.imgur.com/BfvQwOR.gifv), What the malformed packet [looks like](https://i.imgur.com/wgOe0tR.png). 

Let me know what other info you need.

> 2|memer    | [10:57:13] Cluster 11 | SyntaxError: Unexpected token k in JSON at position 0
> 2|memer    |     at JSON.parse (<anonymous>)
> 2|memer    |     at WebSocket.ws.on (/home/dank-memer/Dank-Memer/node_modules/eris/lib/voice/VoiceConnection.js:225:31)
> 2|memer    |     at WebSocket.emit (events.js:180:13)
> 2|memer    |     at WebSocket.emit (domain.js:422:20)
> 2|memer    |     at Receiver._receiver.onmessage (/home/dank-memer/Dank-Memer/node_modules/eris/node_modules/ws/lib/WebSocket.js:141:47)
> 2|memer    |     at Receiver.dataMessage (/home/dank-memer/Dank-Memer/node_modules/eris/node_modules/ws/lib/Receiver.js:389:14)
> 2|memer    |     at Receiver.getData (/home/dank-memer/Dank-Memer/node_modules/eris/node_modules/ws/lib/Receiver.js:330:12)
> 2|memer    |     at Receiver.startLoop (/home/dank-memer/Dank-Memer/node_modules/eris/node_modules/ws/lib/Receiver.js:165:16)
> 2|memer    |     at Receiver.add (/home/dank-memer/Dank-Memer/node_modules/eris/node_modules/ws/lib/Receiver.js:139:10)
> 2|memer    |     at TLSSocket._ultron.on (/home/dank-memer/Dank-Memer/node_modules/eris/node_modules/ws/lib/WebSocket.js:138:22)
> 2|memer    |     at TLSSocket.emit (events.js:180:13)
> 2|memer    |     at TLSSocket.emit (domain.js:422:20)
> 2|memer    |     at addChunk (_stream_readable.js:274:12)
> 2|memer    |     at readableAddChunk (_stream_readable.js:261:11)
> 2|memer    |     at TLSSocket.Readable.push (_stream_readable.js:218:10)
> 2|memer    |     at TLSWrap.onread (net.js:581:20)

**Comment by nikolaspikolas** [comment]
Do you have any examples of what these messages look like?
